use_default_settings: true
server:
  secret_key: "CHANGE_ME"   # 実際はRenderの環境変数で上書き
  image_proxy: true
  limiter: false
ui:
  default_theme: simple
  favicons:
    resolver: duckduckgo
search:
  safe_search: 0
engines:
  - name: yandex
    disabled: true
  - name: bing
    engine: bing
  - name: google
    engine: google
    timeout: 2.0
  - name: duckduckgo
    engine: duckduckgo
    timeout: 2.0
  - name: startpage
    engine: startpage
    timeout: 2.0
  - name: brave
    engine: brave
    timeout: 2.0
